openapi: 3.0.3
info:
  title: User Management
  description: User Management
  version: 1.0.0
  license:
    name: MIT
    url: http://localhost
    
servers:
  - url: 'https://localhost'
paths:
  /users:
    get:
      operationId: getUsers
      summary: 'Gets all the users information'
      description: "Gets all the users information"
      responses:
        200:
          description: "Success response from the server"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
        401:
          description: "Unauthorized access"


